name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Markdown Lint
        uses: articulate/actions-markdownlint@v1